### ISSUE TITLE
[REQUEST] Add the HD TF2 Menu Logo

### ISSUE THREAD

**Issue by impale1** [CriticalFlaw/TF2HUD.Fixes#111]
https://gamebanana.com/mods/27061
This logo was not drawn by him or upscaled by ai, but was taken from the original high quality image from Steam

Without hd logo using your hud (workshop branch):
![1](https://user-images.githubusercontent.com/117596825/222951296-e231a9ff-b459-41b5-af6b-e0b3bcce427f.png)
With hd logo using your hud (workshop branch):
![2](https://user-images.githubusercontent.com/117596825/222951294-e580ee7e-e661-45fb-8fad-93785f51afe5.png)

**Comment by CriticalFlaw** [comment]
This is already included with the mod in the `.extras` folder: https://github.com/CriticalFlaw/TF2HUD.Fixes/tree/main/.extras/materials/vgui/replay/thumbnails

The reason for it being there and not in the base HUD is because it's not being submited to the Steam Workshop (I'd leave that to the original creator of the logo to do if they so choose to).
