### ISSUE TITLE
[REQUEST] Add HD Loading Screens

### ISSUE THREAD

**Issue by impale1** [CriticalFlaw/TF2HUD.Fixes#112]
https://gamebanana.com/mods/285046
#86 Earlier you added a mod that used ai for upscaling so this mod can be allowed to do that too

**Comment by CriticalFlaw** [comment]
This is already included with the mod in the .extras folder: https://github.com/CriticalFlaw/TF2HUD.Fixes/tree/main/.extras/materials/console

The reason for it being there and not in the base HUD is because it's not being submited to the Steam Workshop (I'd leave that to the original creator of the logo to do if they so choose to).
