### ISSUE TITLE
[REQUEST] Add HD Menu Event Backgrounds

### ISSUE THREAD

**Issue by impale1** [CriticalFlaw/TF2HUD.Fixes#113]
https://gamebanana.com/mods/406953
#86 Earlier you added a mod that used ai for upscaling so this mod can be allowed to do that too

**Comment by CriticalFlaw** [comment]
Because these HD images are not going to be submitted to the Steam Workshop with the rest of the HUD changes, I think it's best to leave it to the individual user to add those changes manually. As well as having the original creator submitted the HD artwork to the Steam Workshop directly so they can be officially added.
