### ISSUE TITLE
[BUG] 3D player model on the scoreboard overlaps the player list

### ISSUE THREAD

**Issue by impale1** [CriticalFlaw/TF2HUD.Fixes#117]
**Issue**
Because of this, their heads are covered by the avatar and the player's name.

Soldier (when he's holding a shotgun), demoman (when he's holding a eyelander), heavy, medic, sniper and spy.

**Specifications**
* Branch - main
* Operating system - Linux
* Language - English
* Screen resolution - 1920x1080

**Screenshots**
![bh](https://user-images.githubusercontent.com/117596825/223641047-7d1688c9-5544-473e-a1f3-86a882c1e438.png)

**Comment by CriticalFlaw** [comment]
Fixed in f67e2065e71a03db9d30f39faaa766de997befb3. Here's what it looks like now. It still clips a tiny bit but going lower will make other classes (namely scout) appear too low.
![20230308192347_1](https://user-images.githubusercontent.com/6818236/223883458-66251845-040a-4486-9da4-93c7f20f5f96.jpg)
![20230308192359_1](https://user-images.githubusercontent.com/6818236/223883459-f9095a28-0a3f-4100-bfa1-544cfee967cb.jpg)
