### ISSUE TITLE
[BUG] mp_tournament UI is blocked by tf_use_match_hud 1

### ISSUE THREAD

**Issue by RoseTheFoxGit** [CriticalFlaw/TF2HUD.Fixes#120]
**Issue**
The UI that appears when using mp_tournament 1 is blocked by the match-hud where the timer and classes are displayed.

**Specifications**
16:9 - 1920x1080
Go onto server, switch it to mp_tournament 1 while tf_use_match_hud 1 is enabled
TF2 Hud Editor was used for the installation of TF2HUD.fixes

**Screenshots**
With match hud enabled
![e5ov5WoYsz](https://user-images.githubusercontent.com/80443691/224581447-e191fb51-ed5a-4df8-b0a9-ab64cc6f504b.png)
With match hud disabled
![1g7mCLedf3](https://user-images.githubusercontent.com/80443691/224581450-49dc8691-c9a8-4ef0-87e2-6ff56c6a67d7.png)

**Comment by CriticalFlaw** [comment]
Does the panel reposition itself to be lower after entering `hud_reloadscheme` into console?

**Comment by RoseTheFoxGit** [comment]
https://user-images.githubusercontent.com/80443691/224803956-967200f2-df58-4713-b81c-99e4aea9e5ff.mp4

It does not.

**Comment by CriticalFlaw** [comment]
Fixed in d322fb96250d8443e764227001e83c7b1b0724ee. Unfortunately `resource/ui/hudtournament.res` did not recognize `tf_match` so I had to lower that panel (and the ready/not ready panel) regardless of whether you have mp_tournament 1 or 0.

![20230314195018_1](https://user-images.githubusercontent.com/6818236/225167486-5c10790c-41d7-413c-abdf-9cfae71a2418.jpg)
