### ISSUE TITLE
Making ChatScheme consistent with SourceScheme

### ISSUE THREAD

**Issue by unsubtract** [CriticalFlaw/TF2HUD.Fixes#14]
I found [this GameBanana mod](https://gamebanana.com/guis/26212) that makes the chat window colors consistent with TF2's darker SourceScheme colors used for other windows. 

I'm not on my PC right now to draft a PR but I was wondering if something like this should actually be added, since it's aesthetic and commit 8cfdcde removed many of such changes. If so I can open a PR.

**Comment by CriticalFlaw** [comment]
Could I get a before and after of what the change will look like?

**Comment by TheThunderGuyS** [comment]
Before:
![before](https://user-images.githubusercontent.com/52540509/115166805-05005580-a083-11eb-9228-af38d9e6e648.png)

After:
![after](https://user-images.githubusercontent.com/52540509/115166815-0df12700-a083-11eb-80f5-b13c06278c50.png)

This mod is very old (from 2010) which is why the scrollbar and button border isn't the same.

**Comment by CriticalFlaw** [comment]
Added in 2b45c0c5731e1b68410c35e3f12ee9f5be1e710b
