### ISSUE TITLE
Potential implementation of Jofre-Problem's fixes

### ISSUE THREAD

**Issue by TheThunderGuyS** [CriticalFlaw/TF2HUD.Fixes#15]
[Jofre-Problem/JofreHUD](https://github.com/Jofre-Problem/JofreHUD) is a HUD that "is focused ENTIRELY on optimize the game". 
The readme lists off many fixes to the default HUD, many of which haven't been implemented within TF2HUD.Fixes. This HUD also supposedly makes changes to improve game performance.
I haven't investigated anything myself, but this project could be of some interest.

**Comment by CriticalFlaw** [comment]
Most of the fixes are to correct mistakes in the res files, not necessarily fix visual issues seen in game which is what the focus of this repository is.

Jofre has put a lot of good work into finding and correcting these mistakes, so I suggested he submits these to Valve for their consideration.

I haven't yet seen how it's supposed to improve performance, so that would have to be investigated first.

**Comment by CriticalFlaw** [comment]
Jofre is welcome to implement the changes in this repo into his own though. No reason not to.
