### ISSUE TITLE
Switching between RED and BLU colors on the loadout screen.

### ISSUE THREAD

**Issue by CriticalFlaw** [CriticalFlaw/TF2HUD.Fixes#21]

**Comment by ArmorKeik** [comment]
They say that the code of this mod _"looks like a spaghetti"_ because it has unnecessary files (more information in the comments).

Its creator is a newbie creating HUD, but he kept [his mod](https://gamebanana.com/mods/338493) up to date by accepting suggestions and fixing bugs.

At the moment the mod is only compatible with the default HUD (I tried it in an old version of the mod and it does not have good compatibility with the HUD Fixes).

But I have no doubt that with a little help from you or some other hud creator, he can get his mod to have good compatibility.

**Comment by CriticalFlaw** [comment]
I've previously added these buttons to flawhud and rayshud, it's not too difficult. The buggy part is that the buttons use sv_cheats so they won't work while playing on official servers. Most users already know about that so it's not a big concern.

![20211025194716_1.jpg](https://user-images.githubusercontent.com/6818236/143912871-2c55948b-0d53-431a-aab5-a2d2bb6e1b56.jpg)

**Comment by CriticalFlaw** [comment]
Added to the **community** branch here: e4d7e708b7b931560fb00c6ea4f2163c8f823cdc
