### ISSUE TITLE
[REQUEST] Revert match status to the default state

### ISSUE THREAD

**Issue by impale1** [CriticalFlaw/TF2HUD.Fixes#243]
**Describe the change request.**
> Match Status had a background, but it was removed to fix the bug

Just removing something to fix a bug is not the best solution, better to let Valve fix it

> Match Status was expanded because most players are running 16:9 aspect ratio

If you look at Valve's newest games, you'll see that they are still interested in supporting 4:3 aspect ratio

> Death Panel was removed because it overlapped killfeed

I think the problem is with Killfeed itself and not Match Status, ie you need to make the Killfeed position lower and also Valve needs to unpin Killfeed from spectator bars
![revertmatchstatus](https://github.com/CriticalFlaw/TF2HUD.Fixes/assets/117596825/470e43d3-13cd-48c9-a8f2-abfd45c93a43)

**Comment by CriticalFlaw** [comment]
> Just removing something to fix a bug is not the best solution, better to let Valve fix it

The background panel is hard-coded and persists in most cases. This is not sent to Valve but if they happen to fix it then it will be reverted.

> Match Status was expanded because most players are running 16:9 aspect ratio

It was expanded because past certain number of player it became too cramped. The allotted space is very small and the background does not scale dynamically. It was not because of 16:9 being the norm.

> Death Panel was removed because it overlapped killfeed. I think the problem is with Killfeed itself and not Match Status, ie you need to make the Killfeed position lower and also Valve needs to unpin Killfeed from spectator bars

You'd have to move the killfeed much further down for this to not overlap and because does not respect `if_match` so you'll have people with a lower killfeed who don't use the match HUD. The respawn countdown it incorporated over the class image similarly to how its down in tournament spectator.
