### ISSUE TITLE
[BUG] Player panels are off-screen in a 4:3 aspect ratio

### ISSUE THREAD

**Issue by impale1** [CriticalFlaw/TF2HUD.Fixes#270]
**Describe the issue.**
Advanced spectator hud is used
Operating system - Windows 11 Enterprise 22H2
Resolution - 640x480

**Screenshots**
![image](https://github.com/CriticalFlaw/TF2HUD.Fixes/assets/117596825/cde2393e-2b31-4c3d-9812-f5f3f17fb102)

**Comment by Kruphixx** [comment]
Tournament spectator hud is a tough nut to crack, I don't see a way of fixing this just for 4:3 other than basically reworking it (which is something CriticalFlaw would probably prefer not doing).

**Comment by CriticalFlaw** [comment]
You could put the player panels on the left and make it look like this

![image](https://github.com/CriticalFlaw/TF2HUD.Fixes/assets/6818236/0385ce8c-9677-434f-ab53-8c8b02caa04e)

But the issue becomes that because the player model placement is not relational to the screensize you'd have to have separate values for 4:3, 16:9 and ultra wide resolutions. It becomes a whole mess to maintain.

**Comment by CriticalFlaw** [comment]
Closing as this cannot be fixed for lower resolutions per above comments
