### ISSUE TITLE
Respawn timer has low contrast / visibility

### ISSUE THREAD

**Issue by Sloofy** [CriticalFlaw/TF2HUD.Fixes#47]
### Issue
When in spectator view, if the respawn timer is viewed against a bright surface, it's barely legible. Adding a shadow to the text or bringing back the top cinematic bar may help with improving the visibility.

### Screenshot
![Respawn](https://user-images.githubusercontent.com/18003771/162278287-ff725212-7e65-42ab-b05a-44289859da23.png)

**Comment by CriticalFlaw** [comment]
Because this is a dynamic label, it's not possible to add a separate label to act as the shadow for it. The only other alternative is to put it on the bottom where the black cinematic bar is but I don't know how well it may be received. I think given that the user can just rotate their viewport to better see the respawn timer is sufficient in lieu of coming up with a workaround.
